### ISSUE TITLE
Cannot call Javascript-function from .html-file.

### ISSUE THREAD

**Issue by MJKoedam** [MJKoedam/Crownstone-Intern-Files#1]
### The issue concerns these files:
__login_test.html__
__logintest.js__
_The cloud library is added in the __node_modules__ file. The Javascript code will include that library._

### What I want
I want to call the Javascript file as soon as the 'log in'-button in the Html file has been pressed. The Javascript code will include the cloud-library and proceeds to make a connection to the cloud using the given credentials. Then the code will get the userdata from the cloud and the data will be printed on the console.

### The issues I've encountered
Whenever I use the __require()__-function to include the cloud-library, I get the error:
`logintest.js:1 Uncaught ReferenceError: require is not defined
    at logintest.js:1`

Whenever I use __import__, I get the error:
`Uncaught SyntaxError: Cannot use import statement outside a module`

I am currently stuck with this issue, I haven't been able to try other parts of the code since this is the most important part.

#### note:
In this test-example credentials are hard-coded into the Javascript code, the credentials can not be inserted from the Html-file.

**Comment by mrquincle** [comment]
Hi Mart-Jan,

It sounds like you have to study a bit more about the difference between back-end and front-end. If you have code on the back-end (the nodejs server) it is not necessarily available just like that in the front-end. Would you mind to spend a bit of time studying how to use javascript on the back-end as well as on the front-end? I hope this gives already enough clues. ;-)

Good luck!

**Comment by MJKoedam** [comment]
This issue is now resolved.

Basically I did not quite understand how the server-side of Homey was working together with the login form. Hence the reason I could not figure out how to make a connection to the cloud using a local node.js server.

![Issue 1 - What I thought](https://user-images.githubusercontent.com/58364193/94169940-b6456100-fe8f-11ea-9e9e-0778ac65cf53.png)

I did some more research on the connection with the login form and the Homey and eventually I resolved the issue.

![Issue 1 - What is really going on](https://user-images.githubusercontent.com/58364193/94170061-dd039780-fe8f-11ea-9d8d-8e07229b816c.png)

**Comment by mrquincle** [comment]
Well done!!

**Comment by mrquincle** [comment]
I also understand where you come from. Namely, that a user would like to have immediate feedback if they fill in their username and password and it happens to be incorrect. 

However, the above diagram is definitely necessary. If you restart a Homey the Crownstone app should connect with the Crownstone cloud without intervention of the user. The credentials have indeed to be cached.

There's a best of both worlds though. You probably already guessed. Combine the diagrams and when they fill in their credentials check it with the server and afterwards store the credentials as well. Voila! Immediate feedback if it is wrong, and after a restart the Homey will set up a connection on itself without user interaction.
